alerts = [
"Rusalka (Sedna): Mining Station Discovered | 2000cr - Heat Sword (Blueprint)",
"Psoro (Eris): Enemy Support Squadrons Located | 5000cr - Steel Charge (Artifact)",
"V Prime (Venus): Enemy Diplomat Located | 2000cr",
"Miranda (Uranus): Distress Signal Located | 2000cr",
"Adrastea (Jupiter): Artifact Dig Site Discovered | 7500cr",
"Phithale (Sedna): Enemy Comm Satellite Located | 3400cr",
"Eligor (Europa): Fugitive Located | 2000cr",
"Ose (Europa): Enemy Conspirator Located | 2000cr",
"Vesper (Venus): Detained Refugee Located | 8200cr",
"Methone (Saturn): Artifact Dig Site Discovered | 2000cr",
"Oceanum (Pluto): Enemy Spy Located | 2200cr",
"Ara (Mars): Enemy Assassin Located | 6900cr",
"Iapetus (Saturn): Disable Enemy Satellites | 2000cr",
"Sycorax (Uranus): Enemy Task Force Located | 2000cr",
"Bode (Ceres): Enemy Assassin Located | 2000cr",
"Solium (Eris): Detained Diplomat Located | 2000cr",
"Naiad (Neptune): Distress Signal Located | 2000cr",
"Helene (Saturn): Enemy Recon Unit Located | 2000cr",
"Casta (Ceres): Enemy Diplomat Located | 2000cr",
"Ascar (Eris): Enemy Shock Troops Located | 6100cr",
"Pacific (Earth): Enemy Transmissions Located | 2000cr - Orokin Catalyst (Blueprint)",
"Ascar (Eris): Destroy Research Vessel's Defenses | 8500cr",
"Pacific (Earth): Sabotage Enemy Research Facility | 7700cr",
"Armaros (Europa): Contaminate Research Data | 2000cr - Shotgun Scavenger (Artifact)",
"Martialis (Mars): Disable Communications Network | 5200cr",
"Rusalka (Sedna): Destroy Enemy Devices | 2000cr",
"Naeglar (Eris): Tenno Operative Located | 2000cr",
"Brugia (Eris): Contaminate Research Data | 2000cr",
"Paimon  (Europa): Enemy Comm Station Vulnerable | 3100cr",
"Yemaja (Sedna): Corrupt The Facilities Network Protocols | 2000cr",
"Keeler (Saturn): Destroy Research Station's Defenses | 2000cr",
"Ponaturi (Sedna): Blackmarket Weapons Dealer Located | 2000cr",
"Ishtar (Venus): Research Facility Director Located | 2700cr",
"Ranova (Eris): Network Vulnerability Detected | 2400cr",
"Varro (Ceres): Warframe Discovered | 4000cr",
"Ananke (Jupiter): Abducted Civilian | 2000cr",
"Larissa (Neptune): Enemy Spy Located | 2000cr",
"Rosalind (Uranus): Deactivate Shields | 2000cr",
"Oceanum (Pluto): Sabotage Enemy Research Facility | 2000cr",
"Charybdis (Sedna): Subdue Facility Commander | 6900cr",
"Themisto (Jupiter): Enemy Diplomat Located | 3500cr - Glaive (Blueprint)",
"Histo (Eris): Enemy Ambassador Located | 2000cr - Dual Dagger (Blueprint)",
"Linea (Venus): Enemy Munitions Officer Located | 5900cr - Dark Dagger (Blueprint)",
"Epimetheus (Saturn): Artifact Research Facility Discovered | 5800cr",
"Draco (Ceres): Artifact Depot Discovered | 7500cr - Rejuvenation (Artifact)",
"Sparga (Eris): Blackmarket Trader Located | 7200cr",
"Telesto (Saturn): Plant A Bug Inside Research Facility | 2000cr - Heat Dagger (Blueprint)",
"Varro (Ceres): Fugitive Located | 2000cr",
"Hymeno (Eris): Bypass Data Core Lockout | 2000cr - Rifle Scavenger (Artifact)",
"Ixodes (Eris): Enemy Diplomat Located | 4600cr",
"Ishtar (Venus): Capture And Interrogate Enemy Operative | 2000cr",
"Lillith (Europa): Unknown Distress Signal Located | 2000cr",
"Oceanum (Pluto): Clear Resistance | 2000cr",
"Larissa (Neptune): Upload Virus To Network | 3800cr",
"Rosalind (Uranus): Armory Depot Discovered | 2000cr",
"Arval (Mars): Enemy Escorts Located | 3400cr",
"Giardia (Eris): Weapon Prototype Located | 2000cr",
"Naiad (Neptune): Upload Virus To Network | 2000cr",
"Yemaja (Sedna): Tenno Distress Signal | 2000cr",
"Ultor (Mars): Enemy Task Force Located | 4500cr",
"Egeria (Ceres): Enemy Asteroid Facility Located | 2200cr - Energy Siphon (Artifact)",
"Hades (Pluto): Plant A Bug Inside Research Facility | 2300cr - Rifle Amp (Artifact)",
"Lith (Earth): Tenno Operative Located | 4100cr - Dual Dagger (Blueprint)",
"Giardia (Eris): Upload Virus To Network | 2600cr",
"Zagan (Europa): Corrupt Robotic Archetype Data | 6100cr",
"Psamathe (Neptune): Detained Research Scientist Located | 2500cr",
"Regna (Pluto): Tenno Operative Located | 2000cr",
"Juliet (Uranus): Elite Troops Located | 2000cr",
"Yemaja (Sedna): Supply Depot Located | 2500cr",
"Cyath (Eris): Enemy Spy Located | 2000cr",
"Eligor (Europa): Defeat Enemy Ambush | 7600cr",
"Gradivus (Mars): Secure Excavation Site | 2000cr",
"Cypress (Pluto): Investigate Enemy Facility Distress Signal | 2000cr",
"Everest (Earth): Override Facilities Security Systems | 4700cr",
"Ara (Mars): Enemy Spy Located | 2800cr",
"Elion (Mercury): Investigate Enemy Outpost | 2000cr",
"Rusalka (Sedna): Enemy Spy Located | 2800cr",
"Cypress (Pluto): Upload Virus To Network | 2000cr",
"Palus (Pluto): Enemy Research Located | 2800cr",
"Ascar (Eris): Disable Enemy Satellites | 2700cr - Pistol Scavenger (Artifact)",
"Deimos (Mars): Experimental Ballistics Facility Located | 2000cr",
"Lillith (Europa): Tenno Operative Located | 2000cr - Physique (Artifact)",
"Oestrus (Eris): Transmit Corrupt Data To Computer Core | 5500cr",
"Titan (Saturn): Blackmarket Weapons Dealer Located | 4500cr",
"Ara (Mars): Upload Counter Intel To Enemy Satellites | 2000cr",
"Dione (Saturn): Network Vulnerability Detected | 5200cr",
"Rusalka (Sedna): Enemy Informant Located | 2000cr",
"Portia (Uranus): Disable Navigation Beacon | 2000cr",
"Kappa (Sedna): Blackmarket Weapons Dealer Located | 2000cr",
"Giardia (Eris): Network Vulnerability Detected | 2000cr",
"Portia (Uranus): Enemy Munitions Dump Located | 2000cr",
"Tethys (Saturn): Secret Enemy Facility Located | 2000cr",
"Zagan (Europa): Enemy Security Forces Located | 2000cr",
"Gnathos (Eris): Artifact Research Discovered | 6400cr",
"Graeae (Sedna): Enemy Shock Troops Located | 2000cr",
"Bode (Ceres): Enemy Conspirator Located | 2000cr",
"Yam (Sedna): Enemy Bureaucrat Located | 2000cr",
"Lex (Ceres): Enemy Envoy Located | 2100cr",
"Unda (Venus): Enemy Officer Located | 2000cr"
]


for alert in alerts:
   nodeName= alert.split("(")[0]
   desc = alert.split("):")[1].split("|")[0]
   rewards = alert.split("|")[1]
   print(f'{nodeName} | {desc} | {rewards}')
   